[project]
name = "autobroll"
version = "0.1.0"
description = "Auto B-roll Editing Multi AI Agent"
authors = [
    {name = "Eumgill98",email = "wjdghcks02@gmail.com"}
]
license = {text = "MIT license"}
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "pydantic (>=2.12.5,<3.0.0)",
    "whisperx (>=3.7.4,<4.0.0)",
    "ffmpeg-python (>=0.2.0,<0.3.0)",
    "whisper (>=1.1.10,<2.0.0)",
    "openai-whisper (>=20250625,<20250626)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
